### ISSUE TITLE
Colours missing on find and replace popup

### ISSUE THREAD

**Issue by raffij** [AregGhazaryan/GlassUI-VScode#2]
<img width="448" alt="Screenshot 2021-04-15 at 08 22 02" src="https://user-images.githubusercontent.com/28570/114830102-c5f0ac80-9dc3-11eb-9764-0d52e03e6c43.png">

**Comment by AregGhazaryan** [comment]
Issue is fixed on v1.10 thank you for letting me know. 🙏
