### ISSUE TITLE
Icons not visible in SCM diff popup

### ISSUE THREAD

**Issue by elena-aiello** [AregGhazaryan/GlassUI-VScode#3]
The stage change, revert change, show next change, show previous change and close icons are not visible in the SCM diff popup.

<img width="1204" alt="Screenshot 2021-05-04 at 10 20 57" src="https://user-images.githubusercontent.com/14853243/116977210-731f5c00-acc2-11eb-9bf4-2551bbcdd73c.png">

A workaround (which also fixes issue https://github.com/AregGhazaryan/GlassUI-VScode/issues/2):
```
// settings.json
"workbench.colorCustomizations": {
  "icon.foreground": "#000"
}
```

**Comment by AregGhazaryan** [comment]
Issue is fixed on v1.10 thank you for letting me know. 🙏
